### ISSUE TITLE
Issue with `is_equivalent` using different `Licensing` instances

### ISSUE THREAD

**Issue by tdruez** [nexB/license-expression#21]
While this first code works fine:
```
from license_expression import Licensing

expression = 'gpl-2.0 AND zlib'
licensing = Licensing()
parsed1 = licensing.parse(expression)
parsed2 = licensing.parse(expression)
assert Licensing().is_equivalent(parsed1, parsed2)
```
This second fails:
```
expression = 'gpl-2.0 AND zlib'
parsed1 = Licensing().parse(expression)
parsed2 = Licensing().parse(expression)
assert Licensing().is_equivalent(parsed1, parsed2)
```
It seems to be related to the operator since this last one works as well:
```
expression = 'gpl-2.0'
parsed1 = Licensing().parse(expression)
parsed2 = Licensing().parse(expression)
assert Licensing().is_equivalent(parsed1, parsed2)
```

**Comment by pombredanne** [comment]
@tdruez Thank you. The difference between case 1 and 2 is that you are using two `Licensing` object instances in case 2 rather than the same `Licensing` object in case one. Equivalence is made within the confine of a `Licensing` object instance. So I guess that the resolution can be one of these:
1. workaround: you use a single licensing object
2. whenever a check is requested for two expressions, check that both come from the same licensing. If not ensure that we unparse/reparse one of the two to be from the same `Licensing` as the other
3. add support for doing cross `Licensing` expression comparisons

**Comment by pombredanne** [comment]
@tdruez this not-yet-test commit fixes things up from what I can see. The changes are only in boolean.py in https://github.com/bastikr/boolean.py/tree/proper-equivalence 
Not yet released on Pypi either

**Comment by tdruez** [comment]
@pombredanne thanks++ for the fix!
