### ISSUE TITLE
match license by legalcode url

### ISSUE THREAD

**Issue by faroit** [nexB/license-expression#54]
on some public data providers licenses are given as urls to the legal code... eg. [this entry](https://www.gbif.org/occurrence/3008824353) is referring to `http://creativecommons.org/licenses/by-nc/4.0/legalcode`.

Is there a simple way to use `license-expression` to match these?

**Comment by pombredanne** [comment]
@faroit there are two ways:
1. if you are combining multiple URLs in proper expressions (e.g. combined with AND and OR), then it could make sense to create a collection of license symbols that are URLs. Then they can be parsed alright here
2. Use https://github.com/nexB/scancode-toolkit which does the detection alright . I even pushed a few more rarer CC URLs used for detection just now https://github.com/nexB/scancode-toolkit/commit/c6d42c92f9bbe9c4745d31fb4f47c1533a7b5c30

Where (as in which piece of code) would you use it so that I can provide some help?

**Comment by faroit** [comment]
@pombredanne thanks for your suggestions. Can you give a working example for `1.` to make that more clear?

**Comment by pombredanne** [comment]
@faroit sorry for the late reply!
Here would be a way:
```
>>> from license_expression import LicenseSymbol, Licensing
>>> symbols = [ 
...   LicenseSymbol(key='cc-by-nc-4.0', aliases=['http://creativecommons.org/licenses/by-nc/4.0/legalcode',]),
...   LicenseSymbol(key='cc-by-4.0', aliases=['http://creativecommons.org/licenses/by/4.0/legalcode',]),
... ]
>>> licensing = Licensing(symbols)
>>> expression = 'http://creativecommons.org/licenses/by-nc/4.0/legalcode OR http://creativecommons.org/licenses/by/4.0/legalcode'
>>> licensing.parse(expression)
OR(LicenseSymbol('cc-by-nc-4.0', aliases=('http://creativecommons.org/licenses/by-nc/4.0/legalcode',), is_exception=False), LicenseSymbol('cc-by-4.0', aliases=('http://creativecommons.org/licenses/by/4.0/legalcode',), is_exception=False))
```

**Comment by faroit** [comment]
thats great, sorry for the late response!

**Comment by pombredanne** [comment]
Glad it helped!
