### ISSUE TITLE
Track which version of the SPDX license list is used

### ISSUE THREAD

**Issue by pombredanne** [nexB/license-expression#63]

**Comment by CAM-Gerlach** [comment]
Hey @pombredanne , based off @ofek 's comment in python/peps#2164 , given this appears to effectively vendor/bundle the SPDX license list version, is there a general plan/schedule for keeping it up to date, or any documentation about what that requires? Presently, the released version supports 3.13, while the latest is 3.15; I specified 3.15 in the PR, but we'd probably want to adjust this to the minimum supported here/in scancode, etc at the point the PEP is marked as approved, so that the reference implementation supports the standard as accepted. If its straightforward, I could also potentially help update it, though it isn't terribly critical since the license list is pretty stable nowadays, and AFAIK none of the added licenses are likely used in existing Python projects; on the other hand, since we'll be stuck with it for a while, we would want it to be as recent as possible. Thanks!

**Comment by pombredanne** [comment]
@CAM-Gerlach yes we want to track and keep these updated. 

> If its straightforward, I could also potentially help update it, though it isn't terribly critical since the license list is pretty stable nowadays, and AFAIK none of the added licenses are likely used in existing Python projects; on the other hand, since we'll be stuck with it for a while, we would want it to be as recent as possible. Thanks!

Yes, but I would not want to bind the PEP to an exact license list version. Instead we should just mention version 3.15 or any later version. 

Do you want to have a quick online call together sometimes next week on the PEP and this?

**Comment by CAM-Gerlach** [comment]
> Yes, but I would not want to bind the PEP to an exact license list version. Instead we should just mention version 3.15 or any later version.

Yup, that was your wording there on the license list and SPDX version which I didn't touch, other than bumping the version and clarifying so long as backward compatibility with the specified version was maintained, so as not to invalidate existing valid metadata, per your discussion in pombredanne/spdx-pypi-pep#6 (which I also added a summary of in the rationale section).

> Do you want to have a quick online call together sometimes next week on the PEP and this?

Sure, I'd be happy to. I'm typically most available 18:00 UTC to 02:00 UTC on weekdays (I'm in US CST/UTC-6 right now). I have Zoom, Jitse Meet and Google Meet, if any of those work. If you want to reach out directly, my email is CAM.Gerlach@Gerlach.CAM and I'm on [Gitter](https://gitter.im/CAM-Gerlach). Thanks!

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne has added this at https://github.com/nexB/license-expression/blob/main/src/license_expression/data/license_key_index.json.ABOUT#L3.
